# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    defaults:
      run:
        working-directory: ./TestJuniorDef.FrontEndVue
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      run: |
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          echo "always-auth: true" >> .npmrc
        
    - name: CI
      working-directory: ./TestJuniorDef.FrontEndVue
      run: npm ci
      
    - name: Download Key
      run: |
          echo "https://github.com/giu-napoletano29/EFTest/blob/main/Debug%20Key/testjuniordef.frontendvue.key" >> 'C:\Users\runneradmin\AppData\Roaming\ASP.NET\https\TestJuniorDef.FrontEndVue.key'
          echo "https://github.com/giu-napoletano29/EFTest/blob/main/Debug%20Key/testjuniordef.frontendvue.pem" >> 'C:\Users\runneradmin\AppData\Roaming\ASP.NET\https\TestJuniorDef.FrontEndVue.pem'

    - name: Build
      working-directory: ./TestJuniorDef.FrontEndVue
      run: npm run build --if-present
    - name: test
      working-directory: ./TestJuniorDef.FrontEndVue
      run: npm test
